import { Center, SimpleGrid } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Card from '@/components/card';
import { getAllPosts, getPath, PostMeta } from '@/lib/common';

export async function getStaticProps() {
  const taregetPath = getPath('blog');
  const posts = getAllPosts(taregetPath)
    .slice(0, 9)
    .map((post) => post.meta);
  return { props: { posts } };
}

type Props = {
  posts: PostMeta[];
};
const Blog: NextPage<Props> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      {/* <p>Search blog by topics</p>
      <Flex gap={4} mt={2} mb={8}>
        {tags.map((tag) => (
          <TagLink key={tag} tag={tag} />
        ))}
      </Flex> */}
      <Center>
        <SimpleGrid columns={{ base: 1, lg: 2, xl: 3 }} spacingY={8} spacingX={4}>
          {posts.map((post) => (
            <Card key={post.slug} post={post} />
          ))}
        </SimpleGrid>
      </Center>
    </>
  );
};

export default Blog;
