import { Flex } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Card from '@/components/card';

const Blog: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      {/* TODO:ポストの数だけ要素を変化させるよう修正する。現状3カラムのときに整列が4つポストがあるときにレイアウトが崩れる */}
      <Flex wrap='wrap' justifyContent='center' gap={4} _after={{ content: '" "', display: 'block', width: '320px' }}>
        <Card title='React Hook Formの使い方を解説します' date='2022/09/22' />
      </Flex>
    </>
  );
};

export default Blog;
