import { Box } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Test page</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Box position='relative' w='100%' h='300px'>
        <Image
          src='/images/2022/1016/IMG_5090.JPG'
          alt=''
          layout='fill'
          objectFit='contain'
          placeholder='blur'
          blurDataURL='/images/2022/1016/IMG_5090.JPG'
        />
      </Box>
    </div>
  );
};

export default Home;
