import type { NextPage } from 'next';
import Head from 'next/head';

const Diary: NextPage = () => {
  return (
    <>
      <Head>
        <title>Diary</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      diary製造中
    </>
  );
};

export default Diary;
